title: EGWork
description: "Consultoria em Tecnologia da Informacao"
baseurl: ""
url: "https://egwork.com.br"
author: "Egisberto Vicente da Silva"
email: "egisberto.silva@egwork.com.br"

markdown: kramdown
highlighter: rouge
theme: minima
