title: EGWork
description: "Consultoria em Tecnologia da Informacao"
baseurl: ""
url: "https://egwork.com.br"
author: "Egisberto Vicente da Silva"
email: "egisberto.silva@egwork.com.br"

markdown: kramdown
highlighter: rouge
theme: minima

plugins:
  - jekyll-admin

# Collections for Jekyll Admin
collections:
  includes:
    output: false
  layouts:
    output: false
  assets:
    output: false
  _assets:
    output: false

# Jekyll Admin Configuration
jekyll_admin:
  collections:
    includes:
      output: false
    layouts:
      output: false
    assets:
      output: false
    _assets:
      output: false
